using System.Text;
using System.Text.RegularExpressions;

namespace Stackroot.Core.Services.Php;

public sealed record PhpIniPatchOptions(
    IReadOnlyDictionary<string, string> Directives,
    IReadOnlyList<string> EnabledExtensions,
    IReadOnlyList<string> AllKnownExtensions);

public static class PhpIniMerge
{
    private const string LegacyManagedStart = "; === STACKROOT MANAGED (auto-generated) ===";
    private static readonly Encoding Utf8NoBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);

    public static string? FindBundledPhpIni(string installPath)
    {
        foreach (var name in new[] { "php.ini-development", "php.ini-production", "php.ini" })
        {
            var path = Path.Combine(installPath, name);
            if (File.Exists(path))
            {
                return File.ReadAllText(path);
            }
        }

        return null;
    }

    public static string EnsurePhpIniTemplate(string configRoot, string installPath, string packageId)
    {
        var templatePath = GetTemplatePath(configRoot, packageId);
        if (File.Exists(templatePath))
        {
            return templatePath;
        }

        var bundled = FindBundledPhpIni(PhpExtensionPolicy.ResolvePackageRoot(installPath))
            ?? throw new InvalidOperationException("No php.ini-development template found in the PHP install folder.");

        Directory.CreateDirectory(Path.GetDirectoryName(templatePath)!);
        File.WriteAllText(templatePath, bundled, Utf8NoBom);
        return templatePath;
    }

    public static string? ReadPhpIniTemplate(string configRoot, string packageId)
    {
        var templatePath = GetTemplatePath(configRoot, packageId);
        return File.Exists(templatePath) ? File.ReadAllText(templatePath) : null;
    }

    public static void RestoreIniFromTemplate(string configRoot, string packageId, string iniPath)
    {
        var templatePath = GetTemplatePath(configRoot, packageId);
        if (!File.Exists(templatePath))
        {
            throw new InvalidOperationException("PHP ini template was not found — open PHP settings once to seed it.");
        }

        Directory.CreateDirectory(Path.GetDirectoryName(iniPath)!);
        File.Copy(templatePath, iniPath, overwrite: true);
    }

    public static bool IsLegacyMinimalIni(string content)
    {
        var trimmed = content.TrimStart();
        return trimmed.StartsWith("; Managed by Stackroot", StringComparison.Ordinal)
               || trimmed.StartsWith("; Generated by Stackroot", StringComparison.Ordinal);
    }

    public static string EnsurePhpIniFile(string iniPath, string installPath, string? templateContent = null)
    {
        if (File.Exists(iniPath))
        {
            var existing = File.ReadAllText(iniPath);
            if (!IsLegacyMinimalIni(existing))
            {
                return existing;
            }

            if (!string.IsNullOrWhiteSpace(templateContent))
            {
                File.WriteAllText(iniPath, templateContent, Utf8NoBom);
                return templateContent;
            }

            return existing;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(iniPath)!);
        var bundled = templateContent
            ?? FindBundledPhpIni(PhpExtensionPolicy.ResolvePackageRoot(installPath))
            ?? string.Join(Environment.NewLine,
                "; Stackroot PHP configuration",
                "; No php.ini-development template found in the PHP install folder.");
        File.WriteAllText(iniPath, bundled, Utf8NoBom);
        return bundled;
    }

    private static string GetTemplatePath(string configRoot, string packageId)
        => Path.Combine(configRoot, "php", "templates", $"{packageId}.ini.template");

    public static string EnsurePhpIniFile(string iniPath, string installPath)
        => EnsurePhpIniFile(iniPath, installPath, templateContent: null);

    public static string ApplyPhpIniPatches(string content, PhpIniPatchOptions options)
    {
        var next = MigrateLegacyIniContent(content);

        foreach (var pair in options.Directives)
        {
            next = PatchIniDirective(next, pair.Key, pair.Value);
        }

        var enabled = new HashSet<string>(
            options.EnabledExtensions.Select(static extension => extension.ToLowerInvariant()));

        foreach (var extension in options.AllKnownExtensions)
        {
            next = PatchIniExtension(next, extension, enabled.Contains(extension.ToLowerInvariant()));
        }

        return next;
    }

    public static string PatchIniExtension(string content, string extension, bool enabled)
    {
        if (string.Equals(extension, "opcache", StringComparison.OrdinalIgnoreCase))
        {
            return PatchIniOpcache(content, enabled);
        }

        var kept = content
            .Split(["\r\n", "\n"], StringSplitOptions.None)
            .Where(line => !LineMatchesExtension(line, extension))
            .ToList();

        if (enabled)
        {
            if (kept.Count > 0 && kept[^1] != string.Empty)
            {
                kept.Add(string.Empty);
            }

            kept.Add($"extension={extension}");
        }

        return string.Join(Environment.NewLine, kept);
    }

    public static string PatchIniOpcache(string content, bool enabled)
    {
        var kept = content
            .Split(["\r\n", "\n"], StringSplitOptions.None)
            .Where(line => !LineMatchesOpcache(line))
            .ToList();

        if (enabled)
        {
            if (kept.Count > 0 && kept[^1] != string.Empty)
            {
                kept.Add(string.Empty);
            }

            kept.Add("zend_extension=opcache");
        }

        return string.Join(Environment.NewLine, kept);
    }

    public static string PatchIniDirective(string content, string key, string value)
    {
        var lines = content.Split(["\r\n", "\n"], StringSplitOptions.None);

        var found = false;
        for (var index = 0; index < lines.Length; index++)
        {
            if (!TryParseIniDirectiveLine(lines[index], key, out var leading))
            {
                continue;
            }

            found = true;
            lines[index] = $"{leading}{key} = {value}";
        }

        var next = lines.ToList();
        if (!found)
        {
            if (next.Count > 0 && next[^1] != string.Empty)
            {
                next.Add(string.Empty);
            }

            next.Add($"{key} = {value}");
        }

        return string.Join(Environment.NewLine, next);
    }

    public static string MigrateLegacyIniContent(string content)
    {
        if (content.Contains(LegacyManagedStart, StringComparison.Ordinal))
        {
            return content[..content.IndexOf(LegacyManagedStart, StringComparison.Ordinal)].TrimEnd();
        }

        var trimmed = content.Trim();
        if (!trimmed.StartsWith("; Generated by Stackroot", StringComparison.Ordinal))
        {
            return content;
        }

        return Regex.Replace(trimmed, @"^; Generated by Stackroot[^\n]*\n?", string.Empty).Trim();
    }

    private static bool LineMatchesOpcache(string line)
    {
        if (TryParseExtensionAssignment(line, out var extensionName)
            && extensionName.Contains("opcache", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return TryParseZendExtensionAssignment(line, out var zendName)
               && zendName.Contains("opcache", StringComparison.OrdinalIgnoreCase);
    }

    private static bool LineMatchesExtension(string line, string extension)
    {
        if (!TryParseExtensionAssignment(line, out var extensionName))
        {
            return false;
        }

        return ExtensionNamesMatch(extensionName, extension);
    }

    private static bool ExtensionNamesMatch(string parsedName, string extension)
    {
        if (string.Equals(parsedName, extension, StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var dllName = parsedName.EndsWith(".dll", StringComparison.OrdinalIgnoreCase)
            ? parsedName[..^4]
            : parsedName;
        if (dllName.StartsWith("php_", StringComparison.OrdinalIgnoreCase))
        {
            dllName = dllName[4..];
        }

        return string.Equals(dllName, extension, StringComparison.OrdinalIgnoreCase);
    }

    private static bool TryParseIniDirectiveLine(string line, string key, out string leadingWhitespace)
    {
        leadingWhitespace = string.Empty;
        if (string.IsNullOrWhiteSpace(line))
        {
            return false;
        }

        var index = 0;
        while (index < line.Length && char.IsWhiteSpace(line[index]))
        {
            index++;
        }

        leadingWhitespace = line[..index];
        var remainder = line[index..];
        var semicolonCount = 0;
        while (semicolonCount < remainder.Length && remainder[semicolonCount] == ';')
        {
            semicolonCount++;
        }

        if (semicolonCount > 0)
        {
            remainder = remainder[semicolonCount..].TrimStart();
        }

        var equalsIndex = remainder.IndexOf('=');
        if (equalsIndex <= 0)
        {
            return false;
        }

        var parsedKey = remainder[..equalsIndex].Trim();
        return string.Equals(parsedKey, key, StringComparison.OrdinalIgnoreCase);
    }

    private static bool TryParseExtensionAssignment(string line, out string extensionName)
    {
        extensionName = string.Empty;
        if (string.IsNullOrWhiteSpace(line))
        {
            return false;
        }

        var trimmed = line.TrimStart();
        if (trimmed.StartsWith(';'))
        {
            trimmed = trimmed.TrimStart(';').TrimStart();
        }

        if (!trimmed.StartsWith("extension", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        var equalsIndex = trimmed.IndexOf('=');
        if (equalsIndex < 0)
        {
            return false;
        }

        extensionName = TrimIniValue(trimmed[(equalsIndex + 1)..]);
        return !string.IsNullOrWhiteSpace(extensionName);
    }

    private static bool TryParseZendExtensionAssignment(string line, out string extensionName)
    {
        extensionName = string.Empty;
        if (string.IsNullOrWhiteSpace(line))
        {
            return false;
        }

        var trimmed = line.TrimStart();
        if (trimmed.StartsWith(';'))
        {
            trimmed = trimmed.TrimStart(';').TrimStart();
        }

        if (!trimmed.StartsWith("zend_extension", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        var equalsIndex = trimmed.IndexOf('=');
        if (equalsIndex < 0)
        {
            return false;
        }

        extensionName = TrimIniValue(trimmed[(equalsIndex + 1)..]);
        return !string.IsNullOrWhiteSpace(extensionName);
    }

    private static string TrimIniValue(string raw)
    {
        var value = raw.Trim();
        var commentIndex = value.IndexOf(';');
        if (commentIndex >= 0)
        {
            value = value[..commentIndex].Trim();
        }

        return Path.GetFileName(value);
    }
}
