using Stackroot.Core.Abstractions;

namespace Stackroot.Core.Services;

public static class RedisRuntime
{
    public static string RedisConfigDirectory(StackrootPaths paths)
        => Path.Combine(paths.ConfigRoot, "redis");

    public static string RedisDataDirectory(StackrootPaths paths)
        => Path.Combine(paths.DataRoot, "data", "redis");

    public static string RedisLogPath(StackrootPaths paths)
        => Path.Combine(paths.LogsRoot, "redis.log");

    public static string WriteRedisConfig(StackrootPaths paths, ServicePortSettings settings)
    {
        var confDir = RedisConfigDirectory(paths);
        var dataDir = RedisDataDirectory(paths);
        Directory.CreateDirectory(confDir);
        Directory.CreateDirectory(dataDir);

        var logFile = RedisLogPath(paths).Replace('\\', '/');
        var dataPath = dataDir.Replace('\\', '/');
        var conf = $"""
            # Generated by Stackroot
            bind {settings.Host}
            port {settings.Port}
            dir {dataPath}
            logfile {logFile}
            protected-mode yes
            appendonly no

            """;

        var confPath = Path.Combine(confDir, "redis.conf");
        File.WriteAllText(confPath, conf);
        return confPath;
    }
}
